version: '3'

volumes:
  database_data:
    driver: local

services:

  mysql:
    image: mysql:8.0.18
    command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    expose:
      - 3306
    volumes:
      - database_data:/var/lib/mysql
    env_file:
      - ./mysql.env

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - php
    env_file:
      - ./mysql.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
